
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action ViewAction;
	private global::Gtk.ToggleAction AutoScrollClientAction;
	private global::Gtk.ToggleAction AutoScrollHostAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.Toolbar toolbar1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.VPaned vpaned1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView tvClient;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.TextView tvHost;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.ViewAction = new global::Gtk.Action ("ViewAction", global::Mono.Unix.Catalog.GetString ("View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View");
		w1.Add (this.ViewAction, null);
		this.AutoScrollClientAction = new global::Gtk.ToggleAction ("AutoScrollClientAction", global::Mono.Unix.Catalog.GetString ("AutoScroll Client"), null, null);
		this.AutoScrollClientAction.Active = true;
		this.AutoScrollClientAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("AutoScroll Client");
		w1.Add (this.AutoScrollClientAction, null);
		this.AutoScrollHostAction = new global::Gtk.ToggleAction ("AutoScrollHostAction", global::Mono.Unix.Catalog.GetString ("AutoScroll Host"), null, null);
		this.AutoScrollHostAction.Active = true;
		this.AutoScrollHostAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("AutoScroll Host");
		w1.Add (this.AutoScrollHostAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Artefacts 2");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Gravity = ((global::Gdk.Gravity)(7));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='ViewAction' action='ViewAction'><menuitem name='AutoScrollClientAction' action='AutoScrollClientAction'/><menuitem name='AutoScrollHostAction' action='AutoScrollHostAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'/></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox1.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w4 = new global::Gtk.Viewport ();
		w4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 150;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.tvClient = new global::Gtk.TextView ();
		this.tvClient.CanFocus = true;
		this.tvClient.Name = "tvClient";
		this.GtkScrolledWindow1.Add (this.tvClient);
		this.vpaned1.Add (this.GtkScrolledWindow1);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.GtkScrolledWindow1]));
		w6.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.tvHost = new global::Gtk.TextView ();
		this.tvHost.HeightRequest = 44;
		this.tvHost.CanFocus = true;
		this.tvHost.Name = "tvHost";
		this.GtkScrolledWindow2.Add (this.tvHost);
		this.vpaned1.Add (this.GtkScrolledWindow2);
		w4.Add (this.vpaned1);
		this.GtkScrolledWindow.Add (w4);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w11.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1369;
		this.DefaultHeight = 857;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ConfigureEvent += new global::Gtk.ConfigureEventHandler (this.OnConfigureEvent);
		this.ResizeChecked += new global::System.EventHandler (this.OnResizeChecked);
		this.AutoScrollClientAction.Toggled += new global::System.EventHandler (this.OnAutoScrollClient);
	}
}
