
// This file has been generated by the GUI designer. Do not modify.
namespace Artefacts.TestClient
{
	public partial class DupeProcessWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action DupesAction;
		private global::Gtk.Action harddiskAction1;
		private global::Gtk.Action saveAsAction;
		private global::Gtk.Action FileSystemAction;
		private global::Gtk.Action saveAction;
		private global::Gtk.Action DupeListAction;
		private global::Gtk.Action SelectAllAction;
		private global::Gtk.Action SelectNoneAction;
		private global::Gtk.Action InvertSelectionAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label1;
		private global::Gtk.Entry txtFilename;
		private global::Gtk.IconView viewDupes;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Artefacts.TestClient.DupeProcessWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.DupesAction = new global::Gtk.Action ("DupesAction", global::Mono.Unix.Catalog.GetString ("Dupes"), null, null);
			this.DupesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Dupes");
			w1.Add (this.DupesAction, null);
			this.harddiskAction1 = new global::Gtk.Action ("harddiskAction1", global::Mono.Unix.Catalog.GetString ("Remove Selected"), null, "gtk-harddisk");
			this.harddiskAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Remove Selected");
			w1.Add (this.harddiskAction1, null);
			this.saveAsAction = new global::Gtk.Action ("saveAsAction", global::Mono.Unix.Catalog.GetString ("Apply"), null, "gtk-save-as");
			this.saveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Apply");
			w1.Add (this.saveAsAction, null);
			this.FileSystemAction = new global::Gtk.Action ("FileSystemAction", global::Mono.Unix.Catalog.GetString ("File System"), null, null);
			this.FileSystemAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File System");
			w1.Add (this.FileSystemAction, null);
			this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("Apply"), null, "gtk-save");
			this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Apply");
			w1.Add (this.saveAction, null);
			this.DupeListAction = new global::Gtk.Action ("DupeListAction", global::Mono.Unix.Catalog.GetString ("Dupe List"), null, null);
			this.DupeListAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Dupe List");
			w1.Add (this.DupeListAction, null);
			this.SelectAllAction = new global::Gtk.Action ("SelectAllAction", global::Mono.Unix.Catalog.GetString ("Select all"), null, null);
			this.SelectAllAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Select all");
			w1.Add (this.SelectAllAction, null);
			this.SelectNoneAction = new global::Gtk.Action ("SelectNoneAction", global::Mono.Unix.Catalog.GetString ("Select none"), null, null);
			this.SelectNoneAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Select none");
			w1.Add (this.SelectNoneAction, null);
			this.InvertSelectionAction = new global::Gtk.Action ("InvertSelectionAction", global::Mono.Unix.Catalog.GetString ("Invert Selection"), null, null);
			this.InvertSelectionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Invert Selection");
			w1.Add (this.InvertSelectionAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Artefacts.TestClient.DupeProcessWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("DupeProcessWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Artefacts.TestClient.DupeProcessWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileSystemAction' action='FileSystemAction'><menuitem name='saveAction' action='saveAction'/></menu><menu name='DupeListAction' action='DupeListAction'><menuitem name='SelectAllAction' action='SelectAllAction'/><menuitem name='SelectNoneAction' action='SelectNoneAction'/><menuitem name='InvertSelectionAction' action='InvertSelectionAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("File name:");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.txtFilename = new global::Gtk.Entry ();
			this.txtFilename.CanFocus = true;
			this.txtFilename.Name = "txtFilename";
			this.txtFilename.IsEditable = false;
			this.txtFilename.InvisibleChar = '●';
			this.hbox1.Add (this.txtFilename);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtFilename]));
			w4.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.viewDupes = new global::Gtk.IconView ();
			this.viewDupes.CanFocus = true;
			this.viewDupes.Name = "viewDupes";
			this.viewDupes.Columns = 2;
			this.viewDupes.Reorderable = true;
			this.vbox1.Add (this.viewDupes);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.viewDupes]));
			w6.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 661;
			this.DefaultHeight = 448;
			this.Show ();
			this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
			this.SelectAllAction.Activated += new global::System.EventHandler (this.OnSelectAllActionActivated);
			this.SelectNoneAction.Activated += new global::System.EventHandler (this.OnSelectNoneActionActivated);
			this.InvertSelectionAction.Activated += new global::System.EventHandler (this.OnInvertSelectionActionActivated);
		}
	}
}
