
// This file has been generated by the GUI designer. Do not modify.
namespace Artefacts.TestClient
{
	public partial class DupeFileItem
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action floppyAction;
		private global::Gtk.ToggleAction applyAction;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button btnDupeKeep;
		private global::Gtk.CheckButton chkDupeSelect;
		private global::Gtk.Button btnDupeOpenFolder;
		private global::Gtk.Entry txtDupePath;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Artefacts.TestClient.DupeFileItem
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.floppyAction = new global::Gtk.Action ("floppyAction", null, null, "gtk-floppy");
			w2.Add (this.floppyAction, null);
			this.applyAction = new global::Gtk.ToggleAction ("applyAction", null, null, "gtk-apply");
			w2.Add (this.applyAction, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "Artefacts.TestClient.DupeFileItem";
			// Container child Artefacts.TestClient.DupeFileItem.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnDupeKeep = new global::Gtk.Button ();
			this.btnDupeKeep.CanFocus = true;
			this.btnDupeKeep.Name = "btnDupeKeep";
			this.btnDupeKeep.UseStock = true;
			this.btnDupeKeep.UseUnderline = true;
			this.btnDupeKeep.Label = "gtk-apply";
			this.hbox1.Add (this.btnDupeKeep);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnDupeKeep]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.chkDupeSelect = new global::Gtk.CheckButton ();
			this.chkDupeSelect.CanFocus = true;
			this.chkDupeSelect.Name = "chkDupeSelect";
			this.chkDupeSelect.Label = global::Mono.Unix.Catalog.GetString ("checkbutton3");
			this.chkDupeSelect.DrawIndicator = true;
			this.chkDupeSelect.UseUnderline = true;
			this.hbox1.Add (this.chkDupeSelect);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.chkDupeSelect]));
			w4.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnDupeOpenFolder = new global::Gtk.Button ();
			this.btnDupeOpenFolder.CanFocus = true;
			this.btnDupeOpenFolder.Name = "btnDupeOpenFolder";
			this.btnDupeOpenFolder.UseStock = true;
			this.btnDupeOpenFolder.UseUnderline = true;
			this.btnDupeOpenFolder.Label = "gtk-open";
			this.hbox1.Add (this.btnDupeOpenFolder);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnDupeOpenFolder]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.txtDupePath = new global::Gtk.Entry ();
			this.txtDupePath.CanFocus = true;
			this.txtDupePath.Name = "txtDupePath";
			this.txtDupePath.IsEditable = false;
			this.txtDupePath.InvisibleChar = '●';
			this.hbox1.Add (this.txtDupePath);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtDupePath]));
			w6.Position = 3;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
		}
	}
}
