
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action ViewAction;
	private global::Gtk.ToggleAction AutoScrollClientAction;
	private global::Gtk.ToggleAction AutoScrollHostAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label txtTestName;
	private global::Gtk.Label txtTestTime;
	private global::Gtk.FileChooserButton btnFileChooser;
	private global::Gtk.Button btnStartMain;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label txtTotalSize;
	private global::Gtk.Label txtPostQueue;
	private global::Gtk.Label txtDirectoryQueue;
	private global::Gtk.Label txtCRCQueue;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.VPaned vpaned1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView tvClient;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.TextView tvHost;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.ViewAction = new global::Gtk.Action ("ViewAction", global::Mono.Unix.Catalog.GetString ("View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View");
		w1.Add (this.ViewAction, null);
		this.AutoScrollClientAction = new global::Gtk.ToggleAction ("AutoScrollClientAction", global::Mono.Unix.Catalog.GetString ("AutoScroll Client"), null, null);
		this.AutoScrollClientAction.Active = true;
		this.AutoScrollClientAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("AutoScroll Client");
		w1.Add (this.AutoScrollClientAction, null);
		this.AutoScrollHostAction = new global::Gtk.ToggleAction ("AutoScrollHostAction", global::Mono.Unix.Catalog.GetString ("AutoScroll Host"), null, null);
		this.AutoScrollHostAction.Active = true;
		this.AutoScrollHostAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("AutoScroll Host");
		w1.Add (this.AutoScrollHostAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Artefacts 2");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Gravity = ((global::Gdk.Gravity)(7));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='ViewAction' action='ViewAction'><menuitem name='AutoScrollClientAction' action='AutoScrollClientAction'/><menuitem name='AutoScrollHostAction' action='AutoScrollHostAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtTestName = new global::Gtk.Label ();
		this.txtTestName.Name = "txtTestName";
		this.txtTestName.LabelProp = global::Mono.Unix.Catalog.GetString ("Current Test: (not running)");
		this.hbox2.Add (this.txtTestName);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtTestName]));
		w3.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtTestTime = new global::Gtk.Label ();
		this.txtTestTime.Name = "txtTestTime";
		this.hbox2.Add (this.txtTestTime);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtTestTime]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnFileChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select Trash Folder"), ((global::Gtk.FileChooserAction)(2)));
		this.btnFileChooser.WidthRequest = 340;
		this.btnFileChooser.Name = "btnFileChooser";
		this.hbox2.Add (this.btnFileChooser);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnFileChooser]));
		w5.Position = 2;
		w5.Expand = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnStartMain = new global::Gtk.Button ();
		this.btnStartMain.CanFocus = true;
		this.btnStartMain.Name = "btnStartMain";
		this.btnStartMain.UseUnderline = true;
		this.btnStartMain.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.hbox2.Add (this.btnStartMain);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnStartMain]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		w6.Padding = ((uint)(20));
		// Container child hbox2.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.hbox2.Add (this.fixed1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed1]));
		w7.Position = 4;
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtTotalSize = new global::Gtk.Label ();
		this.txtTotalSize.Name = "txtTotalSize";
		this.txtTotalSize.LabelProp = global::Mono.Unix.Catalog.GetString ("Total Size:");
		this.hbox2.Add (this.txtTotalSize);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtTotalSize]));
		w8.Position = 5;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtPostQueue = new global::Gtk.Label ();
		this.txtPostQueue.Name = "txtPostQueue";
		this.txtPostQueue.LabelProp = global::Mono.Unix.Catalog.GetString ("Post Queue: 0");
		this.hbox2.Add (this.txtPostQueue);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtPostQueue]));
		w9.Position = 6;
		w9.Expand = false;
		w9.Fill = false;
		w9.Padding = ((uint)(20));
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtDirectoryQueue = new global::Gtk.Label ();
		this.txtDirectoryQueue.Name = "txtDirectoryQueue";
		this.txtDirectoryQueue.LabelProp = global::Mono.Unix.Catalog.GetString ("Directory Queue: 0");
		this.hbox2.Add (this.txtDirectoryQueue);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtDirectoryQueue]));
		w10.Position = 7;
		w10.Expand = false;
		w10.Fill = false;
		w10.Padding = ((uint)(20));
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtCRCQueue = new global::Gtk.Label ();
		this.txtCRCQueue.Name = "txtCRCQueue";
		this.txtCRCQueue.LabelProp = global::Mono.Unix.Catalog.GetString ("CRC Queue: 0");
		this.hbox2.Add (this.txtCRCQueue);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtCRCQueue]));
		w11.PackType = ((global::Gtk.PackType)(1));
		w11.Position = 8;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w13 = new global::Gtk.Viewport ();
		w13.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 150;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.tvClient = new global::Gtk.TextView ();
		this.tvClient.CanFocus = true;
		this.tvClient.Name = "tvClient";
		this.GtkScrolledWindow1.Add (this.tvClient);
		this.vpaned1.Add (this.GtkScrolledWindow1);
		global::Gtk.Paned.PanedChild w15 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.GtkScrolledWindow1]));
		w15.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.tvHost = new global::Gtk.TextView ();
		this.tvHost.HeightRequest = 44;
		this.tvHost.CanFocus = true;
		this.tvHost.Name = "tvHost";
		this.GtkScrolledWindow2.Add (this.tvHost);
		this.vpaned1.Add (this.GtkScrolledWindow2);
		w13.Add (this.vpaned1);
		this.GtkScrolledWindow.Add (w13);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w20.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1369;
		this.DefaultHeight = 857;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ConfigureEvent += new global::Gtk.ConfigureEventHandler (this.OnConfigureEvent);
		this.ResizeChecked += new global::System.EventHandler (this.OnResizeChecked);
		this.AutoScrollClientAction.Toggled += new global::System.EventHandler (this.OnAutoScrollClient);
		this.AutoScrollHostAction.Toggled += new global::System.EventHandler (this.OnAutoScrollHost);
	}
}
